--- #YAML:1.0
name:               OSPF-LSDB
version:            1.07
abstract:           ~
author:
    - BLUHM (bluhm@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Validate:       0
    Data::Validate::Struct:  0
    File::Slurp:          0
    List::MoreUtils:      0
    perl:                 5.010000
    Regexp::Common:       0
    Regexp::IPv6:         0
    Test::NoWarnings:     0
    Test::Pod:            0
    Test::Strict:         0
    YAML::Syck:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
